#!/bin/sh
CWD=`pwd`
TMP=${TMP:-/tmp}
PKG=$TMP/package-waterfox

# This is not a source build script.  Rather, it builds a Slackware
# package from the official binary tarball available from mozilla.org.
# Using the official binaries seems like the most direct way to satify
# the Mozilla project's concerns about quality control (and thus to
# provide the most quality-certified package possible), and therefore
# be able to use the official trademarks and logos.
#
# Thanks to the folks at the Mozilla Foundation for permission to
# distribute this, and for all the great work!  :-)

PRGNAM=${PRGNAM:-waterfox}
VERSION=${VERSION:-$(ls waterfox-*.en-US.linux-x86_64.tar.bz2 |cut -f 2- -d -|rev|cut -f 5- -d .|rev)}
ARCH=${ARCH:-x86_64}
BUILD=${BUILD:-1}

if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
rm -rf $PKG
mkdir -p $PKG/usr/lib64
( cd $PKG/usr/lib64
  tar xf $CWD/waterfox-$VERSION.en-US.linux-x86_64.tar.bz2 || exit 1
  mv waterfox waterfox-$VERSION
  ln -sf waterfox-$VERSION waterfox
  cd waterfox-$VERSION
  sed -i -e "s/usr\/local/usr/" waterfox
  #zcat $CWD/mozilla-waterfox-mimeTypes-fix.diff.gz | patch -p1 --verbose --suffix=.orig || exit 1
  #zcat $CWD/waterfox.moz_plugin_path.diff.gz | patch -p1 --verbose --suffix=.orig || exit 1
  rm -f defaults/pref/waterfox.js.orig
  cd $PKG/usr/lib64/waterfox-$VERSION
  # There's really no reason to save this .orig:
  #mv defaults/profile/mimeTypes.rdf defaults/profile/mimeTypes.rdf.orig || exit 1
  #zcat $CWD/mimeTypes.rdf > defaults/profile/mimeTypes.rdf || exit 1
) || exit 1
mkdir -p $PKG/usr/bin
( cd $PKG/usr/bin
  ln -sf /usr/lib64/waterfox-$VERSION/waterfox .
)
mkdir -p $PKG/usr/lib64/mozilla/plugins
mkdir -p $PKG/usr/share/applications
cat $CWD/waterfox.desktop > $PKG/usr/share/applications/waterfox.desktop
mkdir -p $PKG/usr/share/pixmaps
cat $CWD/waterfox.png > $PKG/usr/share/pixmaps/waterfox.png

# These files/directories are usually created if waterfox is run as root, which on many
# systems might (and possibly should) be never.  Therefore, if we don't see them we'll
# put stubs in place to prevent startup errors.
( cd $PKG/usr/lib64/waterfox-$VERSION
  if [ -d extensions/talkback\@mozilla.org ]; then
    if [ ! -r extensions/talkback\@mozilla.org/chrome.manifest ]; then
      echo > extensions/talkback\@mozilla.org/chrome.manifest
    fi
  fi
  if [ ! -d updates ]; then
    mkdir -p updates/0
  fi
)

mkdir $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
makepkg -l y -c n $TMP/$PRGNAM-$VERSION-$ARCH-$BUILD.txz

